# -----------------------------------------------------------------------------
# Basic site settings
# -----------------------------------------------------------------------------

title: "Zhifei (Andy) Li"
first_name: Zhifei (Andy)
middle_name: 
last_name: Li

url: https://andylizf.github.io
baseurl: "" # user site at root

# Emoji favicon or custom image in assets/img/
icon: "⚛️"

# Description for SEO
description: >
  Machine Learning Systems and Cloud Computing. Minimal, fast academic profile.

# Theme
remote_theme: alshedivat/al-folio@v0.14.6

# Locale & language
lang: en

# Navbar / footer
navbar_fixed: true
footer_fixed: true
search_enabled: true

# Blog
blog_name: Zhifei (Andy) Li
blog_nav_title: blog
blog_description: Research updates

# Jekyll
external_links_in_new_tab: true
enable_tooltips: false
enable_darkmode: true
enable_navbar_social: false

# Dimensions
max_width: 930px

# Plugins used by al-folio
plugins:
  - jekyll-remote-theme
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-link-attributes
  - jekyll-paginate-v2
  - jekyll-regex-replace
  - jekyll-scholar
  - jekyll-sitemap
  - jekyll-tabs
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji

# SASS
sass:
  style: compressed

# Scholar (publications)
scholar:
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  sort_by: year, month
  order: descending
  
  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  news:
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Defaults for front matter
defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Output
permalink: /blog/:year/:title/

# Exclude
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile.lock
  - old_content_backup

# The integrity hash is used to ensure that the library is not tampered with.
# Integrity hashes not provided by the libraries were generated using https://www.srihash.org/
third_party_libraries:
  download: false
  bootstrap-table:
    integrity:
      css: sha256-uRX+PiRTR4ysKFRCykT8HLuRCub26LgXJZym3Yeom1c=
      js: sha256-4rppopQE9POKfukn2kEvhJ9Um25Cf6+IDVkARD0xh78=
    url:
      css: https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.4/dist/bootstrap-table.min.css
      js: https://cdn.jsdelivr.net/npm/bootstrap-table@1.22.4/dist/bootstrap-table.min.js
    version: 1.22.4
  chartjs:
    integrity:
      js: sha256-0q+JdOlScWOHcunpUk21uab1jW7C1deBQARHtKMcaB4=
    url:
      js: https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js
    version: 4.4.1
  d3:
    integrity:
      js: sha256-1rA678n2xEx7x4cTZ5x4wpUCj6kUMZEZ5cxLSVSFWxw=
    url:
      js: https://cdn.jsdelivr.net/npm/d3@7.8.5/dist/d3.min.js
    version: 7.8.5
  diff2html:
    integrity:
      css: sha256-IMBK4VNZp0ivwefSn51bswdsrhk0HoMTLc2GqFHFBXg=
      js: sha256-eU2TVHX633T1o/bTQp6iIJByYJEtZThhF9bKz/DcbbY=
    url:
      css: https://cdn.jsdelivr.net/npm/diff2html@3.4.47/bundles/css/diff2html.min.css
      js: https://cdn.jsdelivr.net/npm/diff2html@3.4.47/bundles/js/diff2html-ui.min.js
    version: 3.4.47
  echarts:
    integrity:
      js:
        library: sha256-QvgynZibb2U53SsVu98NggJXYqwRL7tg3FeyfXvPOUY=
        dark_theme: sha256-sm6Ui9w41++ZCWmIWDLC18a6ki72FQpWDiYTDxEPXwU=
    url:
      js:
        library: https://cdn.jsdelivr.net/npm/echarts@5.5.0/dist/echarts.min.js
        dark_theme: https://cdn.jsdelivr.net/npm/echarts@5.5.0/theme/dark-fresh-cut.js
    version: 5.5.0
  google_fonts:
    url:
      fonts: https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:100,300,400,500,700|Material+Icons&display=swap
  highlightjs:
    integrity:
      css:
        light: sha256-Oppd74ucMR5a5Dq96FxjEzGF7tTw2fZ/6ksAqDCM8GY=
        dark: sha256-nyCNAiECsdDHrr/s2OQsp5l9XeY2ZJ0rMepjCT2AkBk=
    url:
      css:
        light: https://cdn.jsdelivr.net/npm/highlight.js@11.9.0/styles/github.min.css
        dark: https://cdn.jsdelivr.net/npm/highlight.js@11.9.0/styles/github-dark.min.css
    version: 11.9.0
  imagesloaded:
    integrity:
      js: sha256-htrLFfZJ6v5udOG+3kNLINIKh2gvoKqwEhHYfTTMICc=
    url:
      js: https://cdn.jsdelivr.net/npm/imagesloaded@5.0.0/imagesloaded.pkgd.min.js
    version: 5.0.0
  img-comparison-slider:
    integrity:
      css: sha256-3qTIuuUWIFnnU3LpQMjqiXc0p09rvd0dmj+WkpQXSR8=
      js: sha256-EXHg3x1K4oIWdyohPeKX2ZS++Wxt/FRPH7Nl01nat1o=
      map: sha256-3wfqS2WU5kGA/ePcgFzJXl5oSN1QsgZI4/edprTgX8w=
    url:
      css: https://cdn.jsdelivr.net/npm/img-comparison-slider@8.0.6/dist/styles.min.css
      js: https://cdn.jsdelivr.net/npm/img-comparison-slider@8.0.6/dist/index.min.js
      map: https://cdn.jsdelivr.net/npm/img-comparison-slider@8.0.6/dist/index.js.map
    version: 8.0.6
  jquery:
    integrity:
      js: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
    url:
      js: https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js
    version: 3.6.0
  leaflet:
    integrity:
      css: sha256-q9ba7o845pMPFU+zcAll8rv+gC+fSovKsOoNQ6cynuQ=
      js: sha256-MgH13bFTTNqsnuEoqNPBLDaqxjGH+lCpqrukmXc8Ppg=
      js_map: sha256-YAoQ3FzREN4GmVENMir8vgHHypC0xfSK3CAxTHCqx1M=
    local:
      images: images/
    url:
      css: https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.css
      images: https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/images/
      js: https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.min.js
      js_map: https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js.map
    version: 1.9.4
  lightbox2:
    integrity:
      css: sha256-uypRbsAiJcFInM/ndyI/JHpzNe6DtUNXaWEUWEPfMGo=
      js: sha256-A6jI5V9s1JznkWwsBaRK8kSeXLgIqQfxfnvdDOZEURY=
    url:
      css: https://cdn.jsdelivr.net/npm/lightbox2@2.11.5/dist/css/lightbox.min.css
      js: https://cdn.jsdelivr.net/npm/lightbox2@2.11.5/dist/js/lightbox.min.js
    version: 2.11.5
  mathjax:
    integrity:
      js: sha256-MASABpB4tYktI2Oitl4t+78w/lyA+D7b/s9GEP0JOGI=
    local:
      fonts: output/chtml/fonts/woff-v2/
    url:
      fonts: https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/output/chtml/fonts/woff-v2/
      js: https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.js
    version: 3.2.2
  masonry:
    integrity:
      js: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
    url:
      js: https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js
    version: 4.2.2
  mdb:
    integrity:
      css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
      css_map: sha256-iYYMNfsJdVZjvsebJulg09miBXM4/GMTJgv1u5EZFFM=
      js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
      js_map: sha256-UPgyn4YNsT0khkBK5553QwhnlbTlU0aa+igyc6qP1bE=
    url:
      css: https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css
      css_map: https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/css/mdb.min.css.map
      js: https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js
      js_map: https://cdn.jsdelivr.net/npm/mdbootstrap@4.20.0/js/mdb.min.js.map
    version: 4.20.0
  medium_zoom:
    integrity:
      js: sha256-ZgMyDAIYDYGxbcpJcfUnYwNevG/xi9OHKaR/8GK+jWc=
    url:
      js: https://cdn.jsdelivr.net/npm/medium-zoom@1.1.0/dist/medium-zoom.min.js
    version: 1.1.0
  mermaid:
    integrity:
      js: sha256-TtLOdUA8mstPoO6sGvHIGx2ceXrrX4KgIItO06XOn8A=
    url:
      js: https://cdn.jsdelivr.net/npm/mermaid@10.7.0/dist/mermaid.min.js
    version: 10.7.0
  photoswipe:
    integrity:
      js: sha256-VCBpdxvrNNxGHNuTdNqK9kPFkev2XY7DYzHdmgaB69Q=
    url:
      css: https://cdn.jsdelivr.net/npm/photoswipe@5.4.4/dist/photoswipe.min.css
      js: https://cdn.jsdelivr.net/npm/photoswipe@5.4.4/dist/photoswipe.esm.min.js
    version: 5.4.4
  photoswipe-lightbox:
    integrity:
      js: sha256-uCw4VgT5DMdwgtjhvU9e98nT2mLZXcw/8WkaTrDd3RI=
    url:
      js: https://cdn.jsdelivr.net/npm/photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js
    version: 5.4.4
  plotly:
    integrity:
      js: sha256-oy6Be7Eh6eiQFs5M7oXuPxxm9qbJXEtTpfSI93dW16Q=
    url:
      js: https://cdn.jsdelivr.net/npm/plotly.js@3.0.1/dist/plotly.min.js
    version: 3.0.1
  polyfill:
    url:
      js: https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
    version: '3'
  pseudocode:
    integrity:
      css: sha256-VwMV//xgBPDyRFVSOshhRhzJRDyBmIACniLPpeXNUdc=
      js: sha256-aVkDxqyzrB+ExUsOY9PdyelkDhn/DfrjWu08aVpqNlo=
    url:
      css: https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.css
      js: https://cdn.jsdelivr.net/npm/pseudocode@2.4.1/build/pseudocode.min.js
    version: 2.4.1
  spotlight:
    integrity:
      css: sha256-Dsvkx8BU8ntk9Iv+4sCkgHRynYSQQFP6gJfBN5STFLY=
    url:
      css: https://cdn.jsdelivr.net/npm/spotlight.js@0.7.8/dist/css/spotlight.min.css
      js: https://cdn.jsdelivr.net/npm/spotlight.js@0.7.8/dist/spotlight.bundle.min.js
    version: 0.7.8
  swiper:
    integrity:
      css: sha256-yUoNxsvX+Vo8Trj3lZ/Y5ZBf8HlBFsB6Xwm7rH75/9E=
      js: sha256-BPrwikijIybg9OQC5SYFFqhBjERYOn97tCureFgYH1E=
      map: sha256-lbF5CsospW93otqvWOIbbhj80CjazrZXvamD7nC7TBI=
    url:
      css: https://cdn.jsdelivr.net/npm/swiper@11.0.5/swiper-bundle.min.css
      js: https://cdn.jsdelivr.net/npm/swiper@11.0.5/swiper-element-bundle.min.js
      map: https://cdn.jsdelivr.net/npm/swiper@11.0.5/swiper-element-bundle.min.js.map
    version: 11.0.5
  swiper-map:
    integrity:
      js: sha256-hlZaH8ySXX97bZaetnrtYlKuhx3oEXFz/s2IXchu6vk=
    url:
      js: https://cdn.jsdelivr.net/npm/swiper@11.1.0/swiper-element-bundle.min.js.map
    version: 11.0.5
  vega:
    integrity:
      js: sha256-Yot/cfgMMMpFwkp/5azR20Tfkt24PFqQ6IQS+80HIZs=
      js_map: sha256-z0x9ICA65dPkZ0JVa9wTImfF6n7AJsKc6WlFE96/wNA=
    url:
      js: https://cdn.jsdelivr.net/npm/vega@5.27.0/build/vega.min.js
      js_map: https://cdn.jsdelivr.net/npm/vega@5.27.0/build/vega.min.js.map
    version: 5.27.0
  vega-embed:
    integrity:
      js: sha256-FPCJ9JYCC9AZSpvC/t/wHBX7ybueZhIqOMjpWqfl3DU=
      js_map: sha256-VBbfSEFYSMdX/rTdGrONEHNP6BprCB7H/LpMMNt/cPA=
    url:
      js: https://cdn.jsdelivr.net/npm/vega-embed@6.24.0/build/vega-embed.min.js
      js_map: https://cdn.jsdelivr.net/npm/vega-embed@6.24.0/build/vega-embed.min.js.map
    version: 6.24.0
  vega-lite:
    integrity:
      js: sha256-TvBvIS5jUN4BSy009usRjNzjI1qRrHPYv7xVLJyjUyw=
      js_map: sha256-l2I4D5JC23Ulsu6e3sKVe5AJ+r+DFkzkKnZS8nUGz28=
    url:
      js: https://cdn.jsdelivr.net/npm/vega-lite@5.16.3/build/vega-lite.min.js
      js_map: https://cdn.jsdelivr.net/npm/vega-lite@5.16.3/build/vega-lite.min.js.map
    version: 5.16.3
  venobox:
    integrity:
      css: sha256-ohJEB0/WsBOdBD+gQO/MGfyJSbTUI8OOLbQGdkxD6Cg=
      js: sha256-LsGXHsHMMmTcz3KqTaWvLv6ome+7pRiic2LPnzTfiSo=
    url:
      css: https://cdn.jsdelivr.net/npm/venobox@2.1.8/dist/venobox.min.css
      js: https://cdn.jsdelivr.net/npm/venobox@2.1.8/dist/venobox.min.js
    version: 2.1.8
