# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: Zhifei Li
shown_title: Zhifei Li (李知非)
first_name: Zhifei
middle_name:
last_name: Li
email: zhifei.li@berkeley.edu
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  A simple, whitespace theme for academics. Based on [*folio](https://github.com/bogoli/-folio) design.
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: Computer Science, UC Berkeley, Machine Learning Systems
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://andylizf.github.io/
baseurl:
last_updated: true # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: false # set to false to disable the back to top button

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

# repo color theme
repo_theme_light: default # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_theme_dark: dark # https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md
repo_trophies:
  enabled: false
  theme_light: flat # https://github.com/ryo-ma/github-profile-trophy
  theme_dark: gitdimmed # https://github.com/ryo-ma/github-profile-trophy

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------
# will use title and url fields
# Take a look to https://github.com/jekyll/jekyll-feed for more customization

rss_icon: false

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: false
search_enabled: false
socials_in_search: false
bib_search: false

# Dimensions
max_width: 840px

# Publication badges
enable_publication_badges:
  altmetric: false
  dimensions: false
  google_scholar: false
  inspirehep: false

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-scholar
  - jekyll-sitemap
  - jemoji
  - jekyll-toc
  - jekyll-email-protect

# SASS
sass:
  style: compressed

# Scholar (publications)
scholar:
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  sort_by: year, month
  order: descending
  # Highlight own name in publication lists
  first_name: ["Zhifei", "Andy"]
  last_name: ["Li"]
  
  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  news:
    output: false
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

# Defaults for front matter
defaults:
  - scope:
      path: ""
      type: news
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Output
permalink: /blog/:year/:title/

# Exclude
exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile.lock
  - old_content_backup

  # Use al-folio defaults for third-party libraries to keep config minimal
