title: Zhifei Li
email: zhifei.li@berkeley.edu
description: Personal academic website
baseurl: ""
url: "https://andylizf.github.io"

# Build settings
markdown: kramdown

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata